
// Auto-generated by AutoPilot on 28-07-2023 at 20:43:06

const express = require('express');
const router = express.Router();

// Route to return top 5 Taylor Swift Songs
router.get('/test/api/email', (req, res) => {
    const taylorSwiftSongs = [
        'Love Story',
        'You Belong With Me',
        'Blank Space',
        'Look What You Made Me Do',
        'Shake It Off'
    ];
    // Sending the top 5 Taylor Swift songs as response
    res.send(taylorSwiftSongs);
});

module.exports = router;

// This code creates a route to return the top 5 Taylor Swift songs as response when the route '/test/api/email' is called.
// The response is sent in the form of an array containing the song names.